[platformio]
boards_dir = boards

[env]
targets = upload, monitor
; platform = platformio/espressif32
platform = espressif32 @ 6.13.0
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
framework = arduino
; framework = espidf
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    ; -Werror
	-DCONFIG_ARDUHAL_LOG_COLORS=1
    -DCORE_DEBUG_LEVEL=3
; board_build.filesystem = spiffs
; board_build.partitions = partitions.csv
; board_build.partitions = no_ota.csv
monitor_filters = esp32_exception_decoder #https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html#filters

[usb_port]
monitor_port = /dev/cu.usbmodem*

[uart_port]
monitor_port = /dev/cu.usbserial*

[env:M5StickC]
board = m5stick-c
; board_build.partitions = no_ota.csv
; build_flags = -Wall -Wextra -Wl,-Map,output.map
monitor_port = ${uart_port.monitor_port}
board_build.partitions = no_ota.csv

[env:M5StickS3]
board = m5stack-sticks3
build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue