#pragma once

#include <Arduino.h>

namespace buddy {

enum class PetAnimState : uint8_t {
  Sleep,
  Idle,
  Busy,
  Attention,
  Celebrate,
  Dizzy,
  Heart,
};

enum class PetLoopMode : uint8_t {
  Loop,
  PingPong,
  PlayOnce,
};

struct DemoFrame {
  const char* rows[32];
};

struct DemoPalette {
  char key;
  uint16_t color;
};

struct PetAnimClip {
  uint8_t start;
  uint8_t count;
  uint16_t frameIntervalMs;
  uint16_t holdOnLastFrameMs;
  PetLoopMode loopMode;
  bool randomIdlePause;
};

struct PetMotionProfile {
  int8_t minOffsetX;
  int8_t maxOffsetX;
  int8_t minOffsetY;
  int8_t maxOffsetY;
  uint16_t minMotionIntervalMs;
  uint16_t maxMotionIntervalMs;
  uint8_t pauseChancePct;
  uint8_t variantChancePct;
  uint8_t rareActionChancePct;
};

constexpr DemoPalette kDemoPalette[] = {
    {'.', 0x0000},
    {'n', 0x3987},
    {'b', 0x7AED},
    {'t', 0xDEDB},
    {'p', 0xDA7A},
    {'w', 0xFFFF},
    {'r', 0xD1E8},
    {'y', 0xFEE0},
    {'h', 0xFB2C},
};

constexpr DemoFrame kDemoFrames[] = {
    // S00 sleep
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "....bbtttt....tttt....ttttbb....",
      "....bbtttt....tttt....ttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "............bb....bb............",
      "............bb....bb............", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "....bbtttt....tttt....ttttbb....",
      "....bbtttt....tttt....ttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbtttttt..rrrr..ttttttbb....",
      "....bbtttttt..rrrr..ttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "..........bb........bb..........",
      "..........bb........bb..........", "............bb....bb............",
      "............bb....bb............", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "....bbtttt....tttt....ttttbb....",
      "....bbtttt....tttt....ttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "..........bbbbbbbbbbbb..........",
      "..........bbbbbbbbbbbb..........", "........bbbb........bbbb........",
      "........bbbb........bbbb........", "..........bb........bb..........",
      "..........bb........bb..........", "................................", "................................"}},

    // S01 idle
    {{"................................", "................n...............", "..............nbbnn.............",
      ".............nbbbbn.............", "............nnbbbnnn............",
      "..........bbbbbbbbbbbb..........", ".........nbbbbbbbbbbbbn.........",
      "........nbbbbbbbbbbbbbbb........", "........bbbbbbbbbbbbbbbb........",
      "...nbbbnbbtttttbbtttttbbnbbbn...", "...bbbbbbbtttttbbtttttbbbbbbb...",
      "..nbbtbbbttttttttttttttbbbtbbn..", "..ntppptbttttttttttttttbtppptn..",
      "..ntppppbttwnttttttnwttbpppptn..", "..ntppppbtnwttttttn.wttbpppptn..",
      "..nbtppnbtnnntnnnnnnnttbnpptbn..", "...nbbbnbbttttttttttttbbnbbbn...",
      "....nnnnbbttttntttttttbbnnnn....", "........bbttttttttttttbb........",
      ".........nbbttttttttbbn.........", "..........nnbbbbbbbbnn..........",
      ".........nbbbbtttbbbbbn..nn.....", ".........nbbbbttttbbbbn.nbb.....",
      "........nbbnbttttttbnbbnnnbn....", "........ntbnbttttttbnbtn..bn....",
      "........nnnnbbttttbbnnnn.nbn....", "..........nnbbtttbbbnnnnbbb.....",
      "...........nbbbbbbbbnnbbbn......", "...........bbbb..bbbbnnnn.......",
      "..........ntttb..btttn..........", "...........nnnn..nnnn...........", "................................"}},
    {{"................................", "................n...............", "..............nbbnn.............",
      ".............nbbbbn.............", "............nnbbbnnn............",
      "..........bbbbbbbbbbbb..........", ".........nbbbbbbbbbbbbn.........",
      "........nbbbbbbbbbbbbbbb........", "........bbbbbbbbbbbbbbbb........",
      "...nbbbnbbtttttbbtttttbbnbbbn...", "...bbbbbbbtttttbbtttttbbbbbbb...",
      "..nbbtbbbttttttttttttttbbbtbbn..", "..ntppptbttttttttttttttbtppptn..",
      "..ntppppbttnnnttttttnnntpppptn..", "..ntppppbtttttttttntttttpppptn..",
      "..nbtppnbtnnntnnnnnnnttbnpptbn..", "...nbbbnbbttttttttttttbbnbbbn...",
      "....nnnnbbttttntttttttbbnnnn....", "........bbttttttttttttbb........",
      ".........nbbttttttttbbn.........", "..........nnbbbbbbbbnn..........",
      ".........nbbbbtttbbbbbn..nn.....", ".........nbbbbttttbbbbn.nbb.....",
      "........nbbnbttttttbnbbnnnbn....", "........ntbnbttttttbnbtn..bn....",
      "........nnnnbbttttbbnnnn.nbn....", "..........nnbbtttbbbnnnnbbb.....",
      "...........nbbbbbbbbnnbbbn......", "...........bbbb..bbbbnnnn.......",
      "..........ntttb..btttn..........", "...........nnnn..nnnn...........", "................................"}},
    {{"................................", "................n...............", "..............nbbnn.............",
      ".............nbbbbn.............", "............nnbbbnnn............",
      "..........bbbbbbbbbbbb..........", ".........nbbbbbbbbbbbbn.........",
      "........nbbbbbbbbbbbbbbb........", "........bbbbbbbbbbbbbbbb........",
      "...nbbbnbbtttttbbtttttbbnbbbn...", "...bbbbbbbtttttbbtttttbbbbbbb...",
      "..nbbtbbbttttttttttttttbbbtbbn..", "..ntppptbttttttttttttttbtppptn..",
      "..ntppppbtwnnttttttnwttbpppptn..", "..ntppppbtwnttttttnwnttbpppptn..",
      "..nbtppnbtnnntnnnnnnnttbnpptbn..", "...nbbbnbbttttttttttttbbnbbbn...",
      "....nnnnbbttttntttttttbbnnnn....", "........bbttttttttttttbb........",
      ".........nbbttttttttbbn.........", "..........nnbbbbbbbbnn..........",
      ".........nbbbbtttbbbbbn..nnnn...", ".........nbbbbttttbbbbn.nbn.....",
      "........nbbnbttttttbnbbnnnbn....", "........ntbnbttttttbnbtn..bn....",
      "........nnnnbbttttbbnnnn.nbn....", "..........nnbbtttbbbnnnnbbb.....",
      "...........nbbbbbbbbnnbbbn......", "...........bbbb..bbbbnnnn.......",
      "..........ntttb..btttn..........", "...........nnnn..nnnn...........", "................................"}},
    {{"................................", "................n...............", "..............nbbnn.............",
      ".............nbbbbn.............", "............nnbbbnnn............",
      "..........bbbbbbbbbbbb..........", ".........nbbbbbbbbbbbbn.........",
      "........nbbbbbbbbbbbbbbb........", "........bbbbbbbbbbbbbbbb........",
      "...nbbbnbbtttttbbtttttbbnbbbn...", "...bbbbbbbtttttbbtttttbbbbbbb...",
      "..nbbtbbbttttttttttttttbbbtbbn..", "..ntppptbttttttttttttttbtppptn..",
      "..ntppppbttnwttttttnnnwbpppptn..", "..ntppppbtn.wnttttn.nnwbpppptn..",
      "..nbtppnbtnnntnnnnnnnttbnpptbn..", "...nbbbnbbttttttttttttbbnbbbn...",
      "....nnnnbbttttntttttttbbnnnn....", "........bbttttttttttttbb........",
      ".........nbbttttttttbbn.........", "..........nnbbbbbbbbnn..........",
      ".........nbbbbtttbbbbbn..nn..n..", ".........nbbbbttttbbbbn.nbb..n..",
      "........nbbnbttttttbnbbnnnbn....", "........ntbnbttttttbnbtn..bn....",
      "........nnnnbbttttbbnnnn.nbn....", "..........nnbbtttbbbnnnnbbb.....",
      "...........nbbbbbbbbnnbbbn......", "...........bbbb..bbbbnnnn.......",
      "..........ntttb..btttn..........", "...........nnnn..nnnn...........", "................................"}},
    {{"................................", "................n...............", "..............nbbnn.............",
      ".............nbbbbn.............", "............nnbbbnnn............",
      "..........bbbbbbbbbbbb..........", ".........nbbbbbbbbbbbbn.........",
      "........nbbbbbbbbbbbbbbb........", "........bbbbbbbbbbbbbbbb........",
      "...nbbbnbbtttttbbtttttbbnbbbn...", "...bbbbbbbtttttbbtttttbbbbbbb...",
      "..nbbtbbbttttttttttttttbbbtbbn..", "..ntppptbttttpttttpttttbtppptn..",
      "..ntppppbttwnttttttnwttbpppptn..", "..ntppppbtn.ttttttn.nttbpppptn..",
      "..nbtppnbtnnnntntntnnttbnpptbn..", "...nbbbnbbttttttttttttbbnbbbn...",
      "....nnnnbbttttntttttttbbnnnn....", "........bbttttttttttttbb........",
      ".........nbbttttttttbbn.........", "..........nnbbbbbbbbnn..........",
      ".........nbbbbtttbbbbbn..nn.....", ".........nbbbbttttbbbbn.nbb.....",
      "........nbbnbttttttbnbbnnnbn....", "........ntbnbttttttbnbtn..bn....",
      "........nnnnbbttttbbnnnn.nbn....", "..........nnbbtttbbbnnnnbbb.....",
      "...........nbbbbbbbbnnbbbn......", "...........bbbb..bbbbnnnn.......",
      "..........ntttb..btttn..........", "...........nnnn..nnnn...........", "................................"}},

    // S02 busy
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttyyyyttttyyyyttbbbb....",
      "....bbbbttyyyyttttyyyyttbbbb....", "....bbttttttyyyyttttyyttttbb....",
      "....bbttttttyyyyttttyyttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "............bbbbbbbb............",
      "............bbbbbbbb............", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbtt..yyyy..yyyy..bbbb....",
      "....bbbbtt..yyyy..yyyy..bbbb....", "....bbttttttyyyyttttyyttttbb....",
      "....bbttttttyyyyttttyyttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "..........bb........bb..........",
      "..........bb........bb..........", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttyyyyttttyyyyttbbbb....",
      "....bbbbttyyyyttttyyyyttbbbb....", "....bbttttttyyyyttttyyttttbb....",
      "....bbttttttyyyyttttyyttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "..........bbbbbbbbbbbb..........",
      "..........bbbbbbbbbbbb..........", "........bbbb........bbbb........",
      "........bbbb........bbbb........", "............bb....bb............",
      "............bb....bb............", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbtt..yyyy..yyyy..bbbb....",
      "....bbbbtt..yyyy..yyyy..bbbb....", "....bbttttttyyyyttttyyttttbb....",
      "....bbttttttyyyyttttyyttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "......bbbb............bbbb......",
      "......bbbb............bbbb......", "............bb....bb............",
      "............bb....bb............", "................................", "................................"}},

    // S03 attention
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttyyyyyyttttbb......",
      "......bbttttttyyyyyyttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "......yy....bb....bb....yy......",
      "......yy....bb....bb....yy......", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttyyyyyyttttbb......",
      "......bbttttttyyyyyyttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "....yy....bbbb....bbbb....yy....",
      "....yy....bbbb....bbbb....yy....", "..........bb........bb..........",
      "..........bb........bb..........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttyyyyyyttttbb......",
      "......bbttttttyyyyyyttttbb......", "....bbbbttyyyyttttyyyyttbbbb....",
      "....bbbbttyyyyttttyyyyttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "....yy....bbbb....bbbb....yy....",
      "....yy....bbbb....bbbb....yy....", "......yy....bb....bb....yy......",
      "......yy....bb....bb....yy......", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttyyyyyyttttbb......",
      "......bbttttttyyyyyyttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "......yy..bbbb....bbbb..yy......",
      "......yy..bbbb....bbbb..yy......", "........yy..bb....bb..yy........",
      "........yy..bb....bb..yy........", "................................", "................................"}},

    // S04 celebrate
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "....yybbbbppttttttttppbbbbyy....",
      "....yybbbbppttttttttppbbbbyy....", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "....yy....bbbb....bbbb....yy....",
      "....yy....bbbb....bbbb....yy....", "......yy....bb....bb....yy......",
      "......yy....bb....bb....yy......", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "....yy..bbppppbbbbppppbb..yy....",
      "....yy..bbppppbbbbppppbb..yy....", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "....yy..bbbbbbbbbbbbbbbbyy......",
      "....yy..bbbbbbbbbbbbbbbbyy......", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "......yy....bb....bb....yy......",
      "......yy....bb....bb....yy......", "................................", "................................"}},
    {{"................................", "................................", "......yy..bbbb....bbbb..yy......",
      "......yy..bbbb....bbbb..yy......", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "....yy....bbbb....bbbb....yy....",
      "....yy....bbbb....bbbb....yy....", "..........bb........bb..........",
      "..........bb........bb..........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "....yybbttttttttttttttttbbyy....",
      "....yybbttttttttttttttttbbyy....", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "....yybbbbttttttttttttbbbbyy....",
      "....yybbbbttttttttttttbbbbyy....", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "......yy....bb....bb....yy......",
      "......yy....bb....bb....yy......", "................................", "................................"}},

    // S05 dizzy
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttyyyyttttyyyyttttbbbb..",
      "....bbbbttyyyyttttyyyyttttbbbb..", "....bbtttt..yyyyttttyyyy..tttt..",
      "....bbtttt..yyyyttttyyyy..tttt..", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "............bb....bb............",
      "............bb....bb............", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbtt..yyyy..yyyy..ttbbbb..",
      "....bbbbtt..yyyy..yyyy..ttbbbb..", "....bbttttyyyyttttyyyyyyttttbb..",
      "....bbttttyyyyttttyyyyyyttttbb..", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbtttttt..rrrr..ttttttbb....",
      "....bbtttttt..rrrr..ttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "........bb............bb........",
      "........bb............bb........", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttyyyyttttyyyyttbbbb....",
      "....bbbbttyyyyttttyyyyttbbbb....", "....bbtttt..yyyyttttyyyy..tttt..",
      "....bbtttt..yyyyttttyyyy..tttt..", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttttrrrrrrrrttttttbb....",
      "....bbttttttrrrrrrrrttttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbbbbbbbbbbbbb........",
      "........bbbbbbbbbbbbbbbb........", "......bbbb............bbbb......",
      "......bbbb............bbbb......", "............bb....bb............",
      "............bb....bb............", "................................", "................................"}},

    // S06 heart
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "..........bbbbhhhhbbbb..........",
      "..........bbbbhhhhbbbb..........", "........bbbbhhhhhhhhbbbb........",
      "........bbbbhhhhhhhhbbbb........", "..........bbhhhhhhhhbb..........",
      "..........bbhhhhhhhhbb..........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "........bbbbhhhhhhhhbbbb........",
      "........bbbbhhhhhhhhbbbb........", "......bbbbhhhhhhhhhhhhbbbb......",
      "......bbbbhhhhhhhhhhhhbbbb......", "........bbbbhhhhhhhhbbbb........",
      "........bbbbhhhhhhhhbbbb........", "................................", "................................"}},
    {{"................................", "................................", "..........bbbb....bbbb..........",
      "..........bbbb....bbbb..........", "........bbppppbbbbppppbb........",
      "........bbppppbbbbppppbb........", "......bbbbppttttttttppbbbb......",
      "......bbbbppttttttttppbbbb......", "......bbttttttttttttttttbb......",
      "......bbttttttttttttttttbb......", "....bbbbttwwwwttttwwwwttbbbb....",
      "....bbbbttwwwwttttwwwwttbbbb....", "....bbttttwwwwttttwwwwttttbb....",
      "....bbttttwwwwttttwwwwttttbb....", "....bbttttttttttttttttttttbb....",
      "....bbttttttttttttttttttttbb....", "....bbttttttnnnnnnttttttttbb....",
      "....bbttttttnnnnnnttttttttbb....", "....bbttttrrrrrrrrrrrrttttbb....",
      "....bbttttrrrrrrrrrrrrttttbb....", "....bbbbttttttttttttttttbbbb....",
      "....bbbbttttttttttttttttbbbb....", "......bbbbttttttttttttbbbb......",
      "......bbbbttttttttttttbbbb......", "..........bbbbhhhhbbbb..........",
      "..........bbbbhhhhbbbb..........", "..........bbhhhhhhhhbb..........",
      "..........bbhhhhhhhhbb..........", "............bbhhhhbb............",
      "............bbhhhhbb............", "................................", "................................"}},
};

constexpr PetAnimClip kPetAnimClips[] = {
    {0, 3, 420, 180, PetLoopMode::PingPong, false},   // sleep
    {3, 5, 260, 160, PetLoopMode::Loop, true},        // idle
    {8, 4, 150, 0, PetLoopMode::Loop, false},         // busy
    {12, 4, 180, 60, PetLoopMode::Loop, false},       // attention
    {16, 4, 130, 120, PetLoopMode::Loop, false},      // celebrate
    {20, 3, 200, 80, PetLoopMode::PingPong, false},   // dizzy
    {23, 3, 140, 160, PetLoopMode::PlayOnce, false},  // heart
};

constexpr PetMotionProfile kPetMotionProfiles[] = {
    {0, 0, 0, 2, 700, 1200, 24, 10, 5},   // sleep
    {-2, 2, 0, 4, 500, 950, 30, 20, 12},  // idle
    {-1, 1, 0, 2, 280, 520, 18, 18, 6},   // busy
    {-1, 1, 0, 2, 240, 420, 22, 10, 4},   // attention
    {-2, 2, 0, 3, 180, 320, 14, 14, 0},   // celebrate
    {-2, 2, 0, 2, 120, 240, 8, 8, 0},     // dizzy
    {-1, 1, -1, 2, 140, 240, 0, 0, 0},    // heart
};

inline const PetAnimClip& clipFor(PetAnimState state) {
  return kPetAnimClips[static_cast<uint8_t>(state)];
}

inline const PetMotionProfile& motionProfileFor(PetAnimState state) {
  return kPetMotionProfiles[static_cast<uint8_t>(state)];
}

}  // namespace buddy
